/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatRoom {
  'id' : bigint,
  'topic' : string,
  'name' : string,
  'createdAt' : Time,
}
export interface Message {
  'id' : bigint,
  'gif' : [] | [string],
  'createdAt' : Time,
  'room' : bigint,
  'text' : string,
  'author' : Principal,
  'image' : [] | [string],
}
export type Time = bigint;
export interface User {
  'bio' : string,
  'username' : string,
  'researchInterests' : string,
  'avatarColor' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<
    [bigint, string, [] | [string], [] | [string]],
    bigint
  >,
  'addRoom' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'getAllRooms' : ActorMethod<[], Array<ChatRoom>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[bigint, bigint, bigint], Array<Message>>,
  'getRoomById' : ActorMethod<[bigint], [] | [ChatRoom]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [User]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];