/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ChatRoom = IDL.Record({
  'id' : IDL.Nat,
  'topic' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const User = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'researchInterests' : IDL.Text,
  'avatarColor' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'gif' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'room' : IDL.Nat,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'image' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'addRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'getAllRooms' : IDL.Func([], [IDL.Vec(ChatRoom)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getRoomById' : IDL.Func([IDL.Nat], [IDL.Opt(ChatRoom)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ChatRoom = IDL.Record({
    'id' : IDL.Nat,
    'topic' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const User = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'researchInterests' : IDL.Text,
    'avatarColor' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'gif' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'room' : IDL.Nat,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'image' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'addRoom' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'getAllRooms' : IDL.Func([], [IDL.Vec(ChatRoom)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getRoomById' : IDL.Func([IDL.Nat], [IDL.Opt(ChatRoom)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };